
package com.bnpparibas.assurance.ea.internal.service.lam.customerquery.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-01T10:31:43.615-05:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "FuncFault", targetNamespace = "http://ea.assurance.bnpparibas.com/internal/service/lam/customerquery/v1")
public class FuncFaultMessage extends Exception {
    
    private com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.FunctionalBaseFaultType funcFault;

    public FuncFaultMessage() {
        super();
    }
    
    public FuncFaultMessage(String message) {
        super(message);
    }
    
    public FuncFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FuncFaultMessage(String message, com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.FunctionalBaseFaultType funcFault) {
        super(message);
        this.funcFault = funcFault;
    }

    public FuncFaultMessage(String message, com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.FunctionalBaseFaultType funcFault, Throwable cause) {
        super(message, cause);
        this.funcFault = funcFault;
    }

    public com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.FunctionalBaseFaultType getFaultInfo() {
        return this.funcFault;
    }
}
