
package com.bnpparibas.assurance.ea.internal.service.lam.customerquery.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-01T10:31:43.726-05:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "TechFault", targetNamespace = "http://ea.assurance.bnpparibas.com/internal/service/lam/customerquery/v1")
public class TechFaultMessage extends Exception {
    
    private com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.TechnicalBaseFaultType techFault;

    public TechFaultMessage() {
        super();
    }
    
    public TechFaultMessage(String message) {
        super(message);
    }
    
    public TechFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public TechFaultMessage(String message, com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.TechnicalBaseFaultType techFault) {
        super(message);
        this.techFault = techFault;
    }

    public TechFaultMessage(String message, com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.TechnicalBaseFaultType techFault, Throwable cause) {
        super(message, cause);
        this.techFault = techFault;
    }

    public com.bnpparibas.assurance.ea.internal.schema.lam.common.exception.v1.TechnicalBaseFaultType getFaultInfo() {
        return this.techFault;
    }
}
